# Config file for automatic testing at travis-ci.org

language: python

cache:
  directories:
    - $HOME/.pip-cache/
python:
  - "3.3"
  - "2.7"

install:
  - pip install pip --upgrade
  - pip install -r requirements/dev.txt  --cache-dir $HOME/.pip-cache

script: py.test tests
